[package]
name = "mine-planning"
version = "0.1.0"
edition = "2024"

[dependencies]
mine-blockmodel = { path = "../mine-blockmodel" }
mine-core = { path = "../mine-core" }
mine-indexing = { path = "../mine-indexing" }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
mine-io = { path = "../mine-io" }
mine-sdk = { path = "../mine-sdk" }

[lints]
workspace = true
