[package]
name = "mine-validation"
version = "0.1.0"
edition = "2024"

[dependencies]
mine-blockmodel = { path = "../mine-blockmodel" }
mine-core = { path = "../mine-core" }
mine-indexing = { path = "../mine-indexing" }
serde = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
