from typing import Any

from .. import BlockModel

_ToolInput = dict[str, Any]
_ToolResponse = dict[str, Any]

def inspect_model(model: BlockModel, input: _ToolInput | None = None) -> _ToolResponse: ...
def validate_model(model: BlockModel, input: _ToolInput | None = None) -> _ToolResponse: ...
def query_blocks(model: BlockModel, input: _ToolInput | None = None) -> _ToolResponse: ...
def aggregate_blocks(model: BlockModel, input: _ToolInput) -> _ToolResponse: ...
def grade_tonnage(model: BlockModel, input: _ToolInput) -> _ToolResponse: ...
def create_scenario(input: _ToolInput) -> _ToolResponse: ...
def evaluate_scenario(input: _ToolInput) -> _ToolResponse: ...
def compare_scenarios(input: _ToolInput) -> _ToolResponse: ...

__all__ = [
    "inspect_model",
    "validate_model",
    "query_blocks",
    "aggregate_blocks",
    "grade_tonnage",
    "create_scenario",
    "evaluate_scenario",
    "compare_scenarios",
]
