from typing import Any

def inspect_model(*args: Any, **kwargs: Any) -> Any: ...
def validate_model(*args: Any, **kwargs: Any) -> Any: ...
def query_blocks(*args: Any, **kwargs: Any) -> Any: ...
def aggregate_blocks(*args: Any, **kwargs: Any) -> Any: ...
def grade_tonnage(*args: Any, **kwargs: Any) -> Any: ...
def create_scenario(*args: Any, **kwargs: Any) -> Any: ...
def evaluate_scenario(*args: Any, **kwargs: Any) -> Any: ...
def compare_scenarios(*args: Any, **kwargs: Any) -> Any: ...
